wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.6.4
    start_time: 1636818669
    t:
      1:
      - 1
      - 9
      4: 3.6.4
      5: 0.12.6
      8:
      - 1
      - 3
      - 5
